// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FillHeartController from "./fill_heart_controller"
application.register("fill-heart", FillHeartController)

import FooterController from "./footer_controller"
application.register("footer", FooterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import RestaurantShowController from "./restaurant_show_controller"
application.register("restaurant-show", RestaurantShowController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
