// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FooterController from "./footer_controller"
application.register("footer", FooterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RestThingController from "./rest_thing_controller"
application.register("rest-thing", RestThingController)

import RestaurantShowController from "./restaurant_show_controller"
application.register("restaurant-show", RestaurantShowController)
