meta_product_name: "WalkIn"
meta_title: "WalkIn lets you see available restaurants all in one place. Tap into the hottest new food spots near you."
meta_description: "Don't you hate it when your friends tell you about an AMAZING restaurant and you can't get a reservation in the next two weeks? If only there was a way of finding the best restaurants in town with availability tonight.. Welcome WalkIn."
meta_image: "cover.png" # should exist in `app/assets/images/`
